# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AnaSayfa.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(902, 585)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: #1a1a2e")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self._2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self._2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self._2.setSpacing(0)
        self._2.setObjectName("_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, -1, 25)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.kamera = QtWidgets.QGraphicsView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.kamera.sizePolicy().hasHeightForWidth())
        self.kamera.setSizePolicy(sizePolicy)
        self.kamera.setStyleSheet("border: 1px solid #22A6B3; selection-background-color: #FF7600;")
        self.kamera.setObjectName("kamera")
        self.horizontalLayout.addWidget(self.kamera)
        self.AnaHarita = QtWebEngineWidgets.QWebEngineView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AnaHarita.sizePolicy().hasHeightForWidth())
        self.AnaHarita.setSizePolicy(sizePolicy)
        self.AnaHarita.setMinimumSize(QtCore.QSize(0, 0))
        self.AnaHarita.setStyleSheet("border: 1px solid #22A6B3;")
        self.AnaHarita.setUrl(QtCore.QUrl("about:blank"))
        self.AnaHarita.setObjectName("AnaHarita")
        self.horizontalLayout.addWidget(self.AnaHarita)
        self._2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_2.setContentsMargins(0, 9, -1, 0)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(-1, 9, 0, 0)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #39ff14;\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.listView = QtWidgets.QListView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listView.sizePolicy().hasHeightForWidth())
        self.listView.setSizePolicy(sizePolicy)
        self.listView.setMinimumSize(QtCore.QSize(500, 400))
        self.listView.setMaximumSize(QtCore.QSize(400, 16777215))
        self.listView.setStyleSheet("background-color: #0F3460;\n"
"color: #FFFFFF;\n"
"border: 2px solid #22A6B3;\n"
"border-radius: 5px;\n"
"padding: 5px;\n"
"selection-background-color: #E94560")
        self.listView.setObjectName("listView")
        self.verticalLayout.addWidget(self.listView)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(0, 9, 0, -1)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_ayrintilar = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_ayrintilar.sizePolicy().hasHeightForWidth())
        self.lineEdit_ayrintilar.setSizePolicy(sizePolicy)
        self.lineEdit_ayrintilar.setMinimumSize(QtCore.QSize(120, 40))
        self.lineEdit_ayrintilar.setStyleSheet("background-color: #0F3460;\n"
"color: #FFFFFF;\n"
"border: 2px solid #22A6B3;\n"
"border-radius: 5px;\n"
"padding: 5px;\n"
"selection-background-color: #E94560")
        self.lineEdit_ayrintilar.setObjectName("lineEdit_ayrintilar")
        self.gridLayout.addWidget(self.lineEdit_ayrintilar, 3, 4, 1, 1)
        self.lineEdit_ekle = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_ekle.sizePolicy().hasHeightForWidth())
        self.lineEdit_ekle.setSizePolicy(sizePolicy)
        self.lineEdit_ekle.setMinimumSize(QtCore.QSize(120, 40))
        self.lineEdit_ekle.setStyleSheet("background-color: #0F3460;\n"
"color: #FFFFFF;\n"
"border: 2px solid #22A6B3;\n"
"border-radius: 5px;\n"
"padding: 5px;\n"
"selection-background-color: #E94560")
        self.lineEdit_ekle.setObjectName("lineEdit_ekle")
        self.gridLayout.addWidget(self.lineEdit_ekle, 1, 4, 1, 1)
        self.Buton_firebase = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Buton_firebase.sizePolicy().hasHeightForWidth())
        self.Buton_firebase.setSizePolicy(sizePolicy)
        self.Buton_firebase.setMinimumSize(QtCore.QSize(120, 40))
        self.Buton_firebase.setStyleSheet("background-color: #E94560; color: white; border-radius: 5px;")
        self.Buton_firebase.setDefault(False)
        self.Buton_firebase.setObjectName("Buton_firebase")
        self.gridLayout.addWidget(self.Buton_firebase, 4, 2, 1, 1)
        self.Buton_ekle = QtWidgets.QPushButton(self.centralwidget)
        self.Buton_ekle.setMinimumSize(QtCore.QSize(120, 40))
        self.Buton_ekle.setBaseSize(QtCore.QSize(0, 0))
        self.Buton_ekle.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Buton_ekle.setStyleSheet("background-color: #E94560; color: white; border-radius: 5px;")
        self.Buton_ekle.setIconSize(QtCore.QSize(16, 16))
        self.Buton_ekle.setObjectName("Buton_ekle")
        self.gridLayout.addWidget(self.Buton_ekle, 1, 1, 1, 1)
        self.Buton_sil = QtWidgets.QPushButton(self.centralwidget)
        self.Buton_sil.setMinimumSize(QtCore.QSize(120, 40))
        self.Buton_sil.setBaseSize(QtCore.QSize(0, 0))
        self.Buton_sil.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Buton_sil.setStyleSheet("background-color: #E94560; color: white; border-radius: 5px;")
        self.Buton_sil.setIconSize(QtCore.QSize(16, 16))
        self.Buton_sil.setObjectName("Buton_sil")
        self.gridLayout.addWidget(self.Buton_sil, 2, 1, 1, 1)
        self.lineEdit_sil = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_sil.sizePolicy().hasHeightForWidth())
        self.lineEdit_sil.setSizePolicy(sizePolicy)
        self.lineEdit_sil.setMinimumSize(QtCore.QSize(120, 40))
        self.lineEdit_sil.setStyleSheet("background-color: #0F3460;\n"
"color: #FFFFFF;\n"
"border: 2px solid #22A6B3;\n"
"border-radius: 5px;\n"
"padding: 5px;\n"
"selection-background-color: #E94560")
        self.lineEdit_sil.setObjectName("lineEdit_sil")
        self.gridLayout.addWidget(self.lineEdit_sil, 2, 4, 1, 1)
        self.Buton_ayrintilar = QtWidgets.QPushButton(self.centralwidget)
        self.Buton_ayrintilar.setMinimumSize(QtCore.QSize(120, 40))
        self.Buton_ayrintilar.setBaseSize(QtCore.QSize(0, 0))
        self.Buton_ayrintilar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Buton_ayrintilar.setStyleSheet("background-color: #E94560; color: white; border-radius: 5px;")
        self.Buton_ayrintilar.setIconSize(QtCore.QSize(16, 16))
        self.Buton_ayrintilar.setObjectName("Buton_ayrintilar")
        self.gridLayout.addWidget(self.Buton_ayrintilar, 3, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(680, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 2, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 3, 0, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout)
        self._2.addLayout(self.horizontalLayout_2)
        self._2.setStretch(1, 10000)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 902, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Toplanma Noktaları"))
        self.Buton_firebase.setText(_translate("MainWindow", "FireBase"))
        self.Buton_ekle.setText(_translate("MainWindow", "Ekle"))
        self.Buton_sil.setText(_translate("MainWindow", "Sil"))
        self.Buton_ayrintilar.setText(_translate("MainWindow", "Ayrıntılar"))
from PyQt5 import QtWebEngineWidgets


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
